### ISSUE TITLE
Explicit Urls are ignored when they differ from the main repo url.

### ISSUE THREAD

**Issue by poetaster** [sailfishos-chum/sailfishos-chum-gui#110]
Although the Screenshots, as here from my fork and not present in the main repo, are used. The Donation url is not, nor is the Help url. 

I would expect explicitly set urls to be used?

It's a bit tricky, since it looks like I'm going to end up doing support (the original author no longer does ubuntu touch or SFOS) and have already done bug fixes and optimization.

```
%if "%{?vendor}" == "chum"
PackageName: Machines vs. Machines
Type: desktop-application
Categories:
 - Game
PackagerName: Mark Washeim (poetaster)
DeveloperName: Michael Zanetti
Custom:
 - Repo: https://github.com/mzanetti/machines-vs-machines-sfos
 - PackagingRepo: https://github.com/poetaster/machines-vs-machines-sfos
Icon: https://github.com/mzanetti/machines-vs-machines-sfos/raw/master/icons/256x256/harbour-machines-vs-machines-sfos.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-1.png
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-2.png
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-3.png
 - https://raw.githubusercontent.com/poetaster/machines-vs-machines-sfos/master/screen-4.png
Url:
 - Help: https://github.com/poetaster/machines-vs-machines-sfos/discussions
 - Bugtracker:https://github.com/mzanetti/machines-vs-machines-sfos/issues
 - Donation: https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=USWAUUU2MD9Z4
%endif
```
